name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.2, 8.1]
        laravel: ['10.*', '11.*', '12.*']
        larastan: ['2.0', '3.0', '3.0']
        dependency-version: [prefer-stable]
        include:
          - laravel: 10.*
            testbench: ^8.0
            database: ^10.0
            php-constraint: ">=8.1"
          - laravel: 11.*
            testbench: ^9.0
            database: ^11.0
            php-constraint: ">=8.2"
          - laravel: 12.*
            testbench: ^10.0
            database: ^12.0
            php-constraint: ">=8.2"
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 11.*
            php: 8.1
          - laravel: 12.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "nesbot/carbon:^2.68" "orchestra/testbench:${{ matrix.testbench }}" "nunomaduro/larastan:^${{ matrix.larastan }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
      - name: Execute tests
        run: vendor/bin/pest
